apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
  namespace: finance-tracker
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: registry.digitalocean.com/finance-tracker-registry/pg-backup:latest
              command: ["/scripts/backup.sh"]

              env:
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: finance-tracker-secrets
                      key: DB_USER

                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: finance-tracker-secrets
                      key: DB_PASSWORD

                - name: DB_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: finance-tracker-config
                      key: DB_NAME

                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: spaces-secret
                      key: AWS_ACCESS_KEY_ID

                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: spaces-secret
                      key: AWS_SECRET_ACCESS_KEY