apiVersion: v1
kind: Secret
metadata:
  name: spaces-secret
  namespace: finance-tracker
type: Opaque
data:
  AWS_ACCESS_KEY_ID: RE84MDFESkJKWEIyNExMNjhDRlk=
  AWS_SECRET_ACCESS_KEY: eDZBN1JMT2tiZWovd3R5ZTc2TUQvZXlLYW9YUzIzSjBiTTdTdjUxSjBzSQ==